create external table measure(measure_name string,measure_id string,measure_start_quarter string, measure_start_date string, measure_end_quarter string,measure_end_date string)row format serde'org.apache.hadoop.hive.serde2.OpenCSVSerde' stored as textfile location '/user/w205/hospital_compare/measures';

Create external table hospitals(provider_id string, hospital_name string, address string, city string, state string, zipcode string, county_name string, phone string, hospital_type string, hospital_ownership string, emergency_services string)row format serde'org.apache.hadoop.hive.serde2.OpenCSVSerde' stored as textfile location '/user/w205/hospital_compare/hospitals';

Create external table effective_care(provider_id string, hospital_name string,address string, city string, state string, zipcode string, county_name string, phone string, condition string, measureID string, measure_name string, score string, sample string, footnote string, measure_start_date string, measure_end_date string)row format serde'org.apache.hadoop.hive.serde2.OpenCSVSerde' stored as textfile location '/user/w205/hospital_compare/effective_care';

Create external table readmission (provider_id string, hospital_name string,address string, city string,state string, zipcode string, county_name string, phone string,measure_name string,measure_id string,compared_to_national string, denominator string, score string, lower_estimate string, higher_estimate string, footnote string,measure_start_date string, measure_end_date string)row format serde'org.apache.hadoop.hive.serde2.OpenCSVSerde' stored as textfile location '/user/w205/hospital_compare/readmission';

Create external table survey_responses(rovider_id string, hospital_name string,address string, city string,state string, zipcode string, county_name string,comm_nurses_achv string, comm_nurses_imp string, comm_nurses_dim string, comm_doc_achv string, comm_doc_imp string, comm_doc_dim string, resp_hosp_staff_achv string,esp_hosp_staff_imp string,esp_hosp_staff_dim string, pain_mgmt_achv string,pain_mgmt_imp string,pain_mgmt_dim string, comm_meds_achv string, comm_meds_impv string,comm_meds_dim string,clean_quiet_achv string,clean_quiet_impv string, clean_quiet_dim string,disch_info_achv string,disch_info_impv string,disch_info_dim string,overall_rating_achv string,overall_rating_impv string,overall_rating_dim string,hcahps_base string, hcahps_consistensy string)row format serde'org.apache.hadoop.hive.serde2.OpenCSVSerde' stored as textfile location '/user/w205/hospital_compare/survey_results';
